// Generated by https://quicktype.io

interface InterfaceAllCategoryResult {
	results: InterfaceAllCategory[];
}

export interface InterfaceAllCategory {
	display_priorities: { [key: string]: number };
	display_priority: number;
	logo_path: string;
	provider_name: string;
	provider_id: number;
}
