// Generated by https://quicktype.io

interface Result {
	page: number;
	results: MoviesGenreType[];
	total_pages: number;
	total_results: number;
}

export interface MoviesGenreType {
	adult: boolean;
	backdrop_path: null | string;
	genre_ids: number[];
	id: number;
	original_language: OriginalLanguage;
	original_title: string;
	overview: string;
	popularity: number;
	poster_path: string;
	release_date: string;
	title: string;
	video: boolean;
	vote_average: number;
	vote_count: number;
}

enum OriginalLanguage {
	En = 'en',
}
