// Generated by https://quicktype.io

export interface NowPlaying {
	dates: Dates;
	page: number;
	results: MoviesNowPlaying[];
	total_pages: number;
	total_results: number;
}

interface Dates {
	maximum: string;
	minimum: string;
}

export interface MoviesNowPlaying {
	adult: boolean;
	backdrop_path: string;
	genre_ids: number[];
	id: number;
	original_language: OriginalLanguage;
	original_title: string;
	overview: string;
	popularity: number;
	poster_path: string;
	release_date: string;
	title: string;
	video: boolean;
	vote_average: number;
	vote_count: number;
}

enum OriginalLanguage {
	En = 'en',
	Es = 'es',
	Fr = 'fr',
}
